In [ ]:
import pandas as pd

# Aula 03 - Criando DataFrame

In [ ]:
data = {
    "Alunos": ['Caio', 'Jorge'],
    "Idade": [16, 15],
    "Nota": [8, 9]
}

In [ ]:
df = pd.DataFrame(data, columns=['Alunos', 'Idade', 'Nota'])

display(df)

  Alunos  Idade  Nota
0   Caio     16     8
1  Jorge     15     9

In [ ]:
# Colher informações rápidas sobre o DataFrame

df.describe()

           Idade      Nota
count   2.000000  2.000000
mean   15.500000  8.500000
std     0.707107  0.707107
min    15.000000  8.000000
25%    15.250000  8.250000
50%    15.500000  8.500000
75%    15.750000  8.750000
max    16.000000  9.000000

In [ ]:
# Excluir uma linha

df = df.drop([0, 1]) # Remover a linha 0 e a 1
df

Empty DataFrame
Columns: [Alunos, Idade, Nota]
Index: []

In [ ]:
df = pd.DataFrame(data, columns=['Alunos', 'Idade', 'Nota'])

In [ ]:
# Excluir uma coluna

df = df.drop('Idade', axis=1) # Remover a coluna 'Idade'
df

  Alunos  Nota
0   Caio     8
1  Jorge     9

# Aula 04 - Extraindo valores do DataFrame

In [ ]:
data = {
    "Alunos": ['Caio', 'Jorge', 'Claudia'],
    "Idade": [16, 15, 16],
    "Nota": [8, 9, 7]
}
df = pd.DataFrame(data, columns=['Alunos', 'Idade', 'Nota'])
display(df)

    Alunos  Idade  Nota
0     Caio     16     8
1    Jorge     15     9
2  Claudia     16     7

In [ ]:
# Quantos itens tem por coluna
df.count()

Alunos    3
Idade     3
Nota      3
dtype: int64

In [ ]:
# Nome das colunas
df.columns

Index(['Alunos', 'Idade', 'Nota'], dtype='object')

In [ ]:
# Quantidade de linhas e colunas
df.shape

(3, 3)

# Aula 05 - Dados estatísticos do DataFrame

In [ ]:
data = {
    "Alunos": ['Caio', 'Jorge', 'Claudia'],
    "Idade": [16, 15, 16],
    "Nota": [8, 9, 7]
}
df = pd.DataFrame(data, columns=['Alunos', 'Idade', 'Nota'])
display(df)

    Alunos  Idade  Nota
0     Caio     16     8
1    Jorge     15     9
2  Claudia     16     7

In [ ]:
# Maiores valores dentro do DataFrame
df['Idade'].max()

df.max()

Alunos    Jorge
Idade        16
Nota          9
dtype: object

In [ ]:
# Menores valores dentro do DataFrame
df.min()

Alunos    Caio
Idade       15
Nota         7
dtype: object

In [ ]:
# Média dos valores das colunas
df.mean()

Idade    15.666667
Nota      8.000000
dtype: float64

In [ ]:
# Mediana do valores
df.median()

Idade    16.0
Nota      8.0
dtype: float64

In [ ]:
# Soma dos valores
df.sum() # Concatena os valores strings

Alunos    CaioJorgeClaudia
Idade                   47
Nota                    24
dtype: object

# Aula 06 - Operações com DataFrame

In [ ]:
data = {
    "Alunos": ['Caio', 'Jorge', 'Claudia'],
    "Idade": [16, 15, 16],
    "Nota": [8, 9, 7]
}
df = pd.DataFrame(data, columns=['Alunos', 'Idade', 'Nota'])
display(df)

    Alunos  Idade  Nota
0     Caio     16     8
1    Jorge     15     9
2  Claudia     16     7

### .add() -> Soma um determinado valor em todas as linhas de uma determinada coluna

In [ ]:
df.add(10)

# Não funciona com strings

TypeError: ignored

In [ ]:
df['Nota'].add(10) # DataFrame não foi alterado

0    18
1    19
2    17
Name: Nota, dtype: int64

### .sub() -> Subtrai um determinado valor em todas as linhas de uma determinada coluna

In [ ]:
df['Idade'].sub(3)

0    13
1    12
2    13
Name: Idade, dtype: int64

### .mul() -> Multiplica um determinado valor em todas as linhas de uma determinada coluna

In [ ]:
df['Idade'].mul(10)

0    160
1    150
2    160
Name: Idade, dtype: int64

### .div() -> Multiplica um determinado valor em todas as linhas de uma determinada coluna

In [ ]:
df['Idade'].div(10)

0    1.6
1    1.5
2    1.6
Name: Idade, dtype: float64

### Acessar itens nas colunas

In [ ]:
nota_um = df['Nota'][1]

print(nota_um)

9

# Aula 07 - Limitando buscas no DataFrame

In [ ]:
data = {
    "Alunos": ['Caio', 'Jorge', 'Claudia'],
    "Idade": [16, 15, 16],
    "Nota": [8, 9, 7]
}
df = pd.DataFrame(data, columns=['Alunos', 'Idade', 'Nota'])
display(df)

    Alunos  Idade  Nota
0     Caio     16     8
1    Jorge     15     9
2  Claudia     16     7

In [ ]:
# Mostrar as 5 primeiras linhas
df.head()

    Alunos  Idade  Nota
0     Caio     16     8
1    Jorge     15     9
2  Claudia     16     7

In [ ]:
# Mostrar as 5 últimas linhas
df.tail()

    Alunos  Idade  Nota
0     Caio     16     8
1    Jorge     15     9
2  Claudia     16     7

In [ ]:
# Limitar os dados 
df.loc[df['Nota'] >= 9 ]

  Alunos  Idade  Nota
1  Jorge     15     9

# Aula 08 - Lendo arquivos .csv

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/02 - Colab Notebooks/02 - Em progresso/Algoritmos-de-Machine-Learning/Seção 1 - Conhecimentos essenciais/servicos.csv')

In [ ]:
display(df)

     Código  ... Subclasse
0        19  ...       NaN
1        27  ...       NaN
2        35  ...       NaN
3        43  ...       NaN
4        51  ...       NaN
..      ...  ...       ...
495    5029  ...       NaN
496    5037  ...       NaN
497    5045  ...       NaN
498    5053  ...       NaN
499    5061  ...       NaN

[500 rows x 9 columns]

In [ ]:
df.shape

(500, 9)

In [ ]:
df.describe()

# Nota-se que o CPC tem valores NaN

            Código           CPC
count   500.000000    481.000000
mean   2509.780000  10948.887734
std    1445.987758  21632.225927
min      19.000000    541.000000
25%    1258.000000    871.000000
50%    2509.000000   5459.000000
75%    3753.250000   8599.000000
max    5061.000000  97990.000000

In [ ]:
df.columns

Index(['Código', 'Descrição', 'Unidade medida', 'CPC', 'Seção', 'Divisão',
       'Grupo', 'Classe', 'Subclasse'],
      dtype='object')

In [ ]:
df.count()

Código            500
Descrição         500
Unidade medida    481
CPC               481
Seção             481
Divisão           481
Grupo             481
Classe            288
Subclasse          39
dtype: int64

In [ ]:
# Exclui-se CPC pois não sei o que é
# Exclui-se Subclasse pois tem muitos valores nulos
df = df.drop(['CPC', 'Subclasse'], axis=1)
display(df)

     Código  ...                                             Classe
0        19  ...  8319: OUTROS SERVIÇOS DE GERÊNCIA/GESTÃO, EXCE...
1        27  ...  8319: OUTROS SERVIÇOS DE GERÊNCIA/GESTÃO, EXCE...
2        35  ...  8319: OUTROS SERVIÇOS DE GERÊNCIA/GESTÃO, EXCE...
3        43  ...  8319: OUTROS SERVIÇOS DE GERÊNCIA/GESTÃO, EXCE...
4        51  ...  8319: OUTROS SERVIÇOS DE GERÊNCIA/GESTÃO, EXCE...
..      ...  ...                                                ...
495    5029  ...  8729: SERVIÇOS DE MANUTENÇÃO E REPARO DE OUTRO...
496    5037  ...  8729: SERVIÇOS DE MANUTENÇÃO E REPARO DE OUTRO...
497    5045  ...  8729: SERVIÇOS DE MANUTENÇÃO E REPARO DE OUTRO...
498    5053  ...  8729: SERVIÇOS DE MANUTENÇÃO E REPARO DE OUTRO...
499    5061  ...  8729: SERVIÇOS DE MANUTENÇÃO E REPARO DE OUTRO...

[500 rows x 7 columns]

In [ ]:
df.count()

Código            500
Descrição         500
Unidade medida    481
Seção             481
Divisão           481
Grupo             481
Classe            288
dtype: int64